FROM node:20-alpine AS build

WORKDIR /app

COPY frontend/package.json frontend/tsconfig.json frontend/tsconfig.app.json frontend/vite.config.ts ./
RUN npm install

COPY frontend/index.html ./index.html
COPY frontend/src ./src

RUN npm run build

FROM nginx:1.27-alpine

COPY infra/frontend/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
