FROM apache/airflow:3.1.4

USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends docker.io \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow

COPY requirements/requirements-ingestion.txt /tmp/
RUN pip install --no-cache-dir -r /tmp/requirements-ingestion.txt
