from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class DomainDefinition:
    id: str
    label: str
    query_keywords: tuple[str, ...]


DOMAIN_DEFINITIONS: tuple[DomainDefinition, ...] = (
    DomainDefinition(
        id="politics",
        label="정치·정책",
        query_keywords=(
            "대통령",
            "국회",
            "정부",
            "정당",
            "선거",
            "외교",
            "안보",
            "검찰",
            "사법",
            "행정",
            "사설",
            "칼럼",
            "논설",
            "여론",
        ),
    ),
    DomainDefinition(
        id="economy",
        label="경제·금융·부동산",
        query_keywords=(
            "경제",
            "금리",
            "물가",
            "환율",
            "수출",
            "무역",
            "기업",
            "산업",
            "고용",
            "소비",
            "코스피",
            "코스닥",
            "증시",
            "주식",
            "채권",
            "은행",
            "보험",
            "부동산",
            "아파트",
            "분양",
        ),
    ),
    DomainDefinition(
        id="society",
        label="지역·사회",
        query_keywords=(
            "사회",
            "사건사고",
            "교육",
            "노동",
            "의료",
            "복지",
            "환경",
            "재난",
            "경찰",
            "법원",
            "서울",
            "수도권",
            "부산",
            "대구",
            "광주",
            "대전",
            "울산",
            "강원",
            "충청",
            "전라",
            "경상",
            "제주",
            "미국",
            "중국",
            "일본",
            "유럽",
            "러시아",
            "중동",
            "우크라이나",
            "북한",
            "국제유가",
            "세계경제",
        ),
    ),
    DomainDefinition(
        id="tech_science",
        label="IT·과학·테크",
        query_keywords=(
            "AI",
            "인공지능",
            "생성형 AI",
            "반도체",
            "배터리",
            "로봇",
            "바이오",
            "우주",
            "기후기술",
            "사이버보안",
        ),
    ),
    DomainDefinition(
        id="culture_life",
        label="엔터·문화·생활",
        query_keywords=(
            "문화",
            "책",
            "전시",
            "공연",
            "여행",
            "건강",
            "생활",
            "음식",
            "패션",
            "종교",
            "연예",
            "K팝",
            "아이돌",
            "드라마",
            "영화",
            "OTT",
            "방송",
            "가요",
            "배우",
            "콘서트",
        ),
    ),
    DomainDefinition(
        id="sports",
        label="스포츠",
        query_keywords=(
            "야구",
            "축구",
            "농구",
            "배구",
            "골프",
            "올림픽",
            "월드컵",
            "K리그",
            "프로야구",
            "e스포츠",
        ),
    ),
)

DOMAIN_LABELS = {domain.id: domain.label for domain in DOMAIN_DEFINITIONS}
